{"name": "test_mul[get_mul_datas0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "slef = <pytest_test.pytest_shizhan.pytest_calc.TestCalc object at 0x0000024890CF9BB0>, init_calc = <pytest_test.pytest_shizhan.python_code.daic.Calculator object at 0x0000024890C81EE0>\nget_mul_datas = [1, 1, 2]\n\n    @pytest.mark.run(ordder=3)\n    def test_mul(slef, init_calc, get_mul_datas):\n        result = init_calc.mul(get_mul_datas[0], get_mul_datas[1])\n        expect = get_mul_datas[2]\n>       assert result == expect\nE       assert 1 == 2\n\npytest_calc.py:51: AssertionError"}, "parameters": [{"name": "get_mul_datas", "value": "[1, 1, 2]"}], "start": 1614321518181, "stop": 1614321518181, "uuid": "1d299139-ad95-4994-a4d4-5ae6c5645ff1", "historyId": "3de93696ba462e569090d67a4c529380", "testCaseId": "df122dab73e4f2908da372187ee1b4d8", "fullName": "pytest_calc.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(ordder=3)"}, {"name": "suite", "value": "pytest_calc"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "LAPTOP-3I6ADUJA"}, {"name": "thread", "value": "1128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_calc"}]}